name: ooi_sonar
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - ipykernel
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - python
  - scipy
  - scikit-image
  - scikit-learn
  - tensorly
  - xarray
